"""contribution_grants

Revision ID: 015523bcd9fd
Revises: af33f832b4ac
Create Date: 2026-07-22 07:48:11.801858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015523bcd9fd'
down_revision: Union[str, Sequence[str], None] = 'af33f832b4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution_grants',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('IDEA', 'GOAL', 'EXTRA_WORK', 'SALES', name='contribtype', native_enum=False, length=20), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('granted_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['granted_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribution_grants_employee_id'), 'contribution_grants', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contribution_grants_employee_id'), table_name='contribution_grants')
    op.drop_table('contribution_grants')
    # ### end Alembic commands ###
