"""invite_keys, join_requests, rank nullable

Revision ID: 15142a0a9d39
Revises: 678cea7fd4ab
Create Date: 2026-07-22 06:25:40.442084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15142a0a9d39'
down_revision: Union[str, Sequence[str], None] = '678cea7fd4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='joinrequeststatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_email'), 'join_requests', ['email'], unique=False)
    op.create_table('invite_keys',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'MEMBER', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('UNUSED', 'USED', 'EXPIRED', name='invitestatus', native_enum=False, length=20), nullable=False),
    sa.Column('issued_by_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_keys_code'), 'invite_keys', ['code'], unique=True)
    op.alter_column('employees', 'rank',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'rank',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_invite_keys_code'), table_name='invite_keys')
    op.drop_table('invite_keys')
    op.drop_index(op.f('ix_join_requests_email'), table_name='join_requests')
    op.drop_table('join_requests')
    # ### end Alembic commands ###
