"""members, registrations

Revision ID: 3a1d81d7a46b
Revises: ff8a4cbd0ec9
Create Date: 2026-07-22 07:03:41.475869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1d81d7a46b'
down_revision: Union[str, Sequence[str], None] = 'ff8a4cbd0ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('owner_trainer_id', sa.String(length=36), nullable=False),
    sa.Column('referrer_member_id', sa.String(length=36), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['owner_trainer_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['referrer_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_branch_id'), 'members', ['branch_id'], unique=False)
    op.create_index(op.f('ix_members_owner_trainer_id'), 'members', ['owner_trainer_id'], unique=False)
    op.create_table('registrations',
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('trainer_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('NEW', 'RENEWAL', name='registrationtype', native_enum=False, length=20), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('used_sessions', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.Column('session_unit_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', name='registrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_member_id'), 'registrations', ['member_id'], unique=False)
    op.create_index(op.f('ix_registrations_trainer_id'), 'registrations', ['trainer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrations_trainer_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_member_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_members_owner_trainer_id'), table_name='members')
    op.drop_index(op.f('ix_members_branch_id'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
