"""drop employee barcode

Revision ID: 3c63fda64d94
Revises: e5f5add80ce9
Create Date: 2026-07-23 09:42:05.673866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c63fda64d94'
down_revision: Union[str, Sequence[str], None] = 'e5f5add80ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_barcode'), table_name='employees')
    op.drop_column('employees', 'barcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('barcode', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_employees_barcode'), 'employees', ['barcode'], unique=True)
    # ### end Alembic commands ###
