"""payslip_submit_workflow

Revision ID: 3fc796ddaecc
Revises: 3c63fda64d94
Create Date: 2026-07-24 02:48:44.566996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc796ddaecc'
down_revision: Union[str, Sequence[str], None] = '3c63fda64d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payslips', sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='payslipstatus', native_enum=False, length=20), server_default='DRAFT', nullable=False))
    op.add_column('payslips', sa.Column('reject_reason', sa.Text(), nullable=True))
    op.add_column('payslips', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payslips', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payslips', sa.Column('decided_by_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'payslips', 'employees', ['decided_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payslips', type_='foreignkey')
    op.drop_column('payslips', 'decided_by_id')
    op.drop_column('payslips', 'decided_at')
    op.drop_column('payslips', 'submitted_at')
    op.drop_column('payslips', 'reject_reason')
    op.drop_column('payslips', 'status')
    # ### end Alembic commands ###
