"""project_requests table

Revision ID: 46006846a4bf
Revises: 8ba67c3e4737
Create Date: 2026-07-24 09:42:58.046695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46006846a4bf'
down_revision: Union[str, Sequence[str], None] = '8ba67c3e4737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_requests',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('EXTENSION', 'OVERDUE', name='projectrequesttype', native_enum=False, length=20), nullable=False),
    sa.Column('new_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='projectrequeststatus', native_enum=False, length=20), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=False),
    sa.Column('decided_by_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_requests_project_id'), 'project_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_requests_requested_by_id'), 'project_requests', ['requested_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_requests_requested_by_id'), table_name='project_requests')
    op.drop_index(op.f('ix_project_requests_project_id'), table_name='project_requests')
    op.drop_table('project_requests')
    # ### end Alembic commands ###
