"""score_events, session_signs

Revision ID: 4ff640988ab8
Revises: 3a1d81d7a46b
Create Date: 2026-07-22 07:25:09.771820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff640988ab8'
down_revision: Union[str, Sequence[str], None] = '3a1d81d7a46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_events',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('ENV', 'PEER', 'KINDNESS', 'CLASS', 'CONTRIB', 'OPERATOR', name='scorecategory', native_enum=False, length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_ref_id', sa.String(length=36), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_events_branch_id'), 'score_events', ['branch_id'], unique=False)
    op.create_index(op.f('ix_score_events_employee_id'), 'score_events', ['employee_id'], unique=False)
    op.create_index(op.f('ix_score_events_period'), 'score_events', ['period'], unique=False)
    op.create_table('session_signs',
    sa.Column('registration_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('performed_by_trainer_id', sa.String(length=36), nullable=False),
    sa.Column('session_no', sa.Integer(), nullable=False),
    sa.Column('signature_url', sa.String(length=500), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['performed_by_trainer_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_signs_member_id'), 'session_signs', ['member_id'], unique=False)
    op.create_index(op.f('ix_session_signs_performed_by_trainer_id'), 'session_signs', ['performed_by_trainer_id'], unique=False)
    op.create_index(op.f('ix_session_signs_registration_id'), 'session_signs', ['registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_signs_registration_id'), table_name='session_signs')
    op.drop_index(op.f('ix_session_signs_performed_by_trainer_id'), table_name='session_signs')
    op.drop_index(op.f('ix_session_signs_member_id'), table_name='session_signs')
    op.drop_table('session_signs')
    op.drop_index(op.f('ix_score_events_period'), table_name='score_events')
    op.drop_index(op.f('ix_score_events_employee_id'), table_name='score_events')
    op.drop_index(op.f('ix_score_events_branch_id'), table_name='score_events')
    op.drop_table('score_events')
    # ### end Alembic commands ###
