"""kindness_surveys, score createdby nullable

Revision ID: 684a81169a44
Revises: 015523bcd9fd
Create Date: 2026-07-22 07:51:24.993309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684a81169a44'
down_revision: Union[str, Sequence[str], None] = '015523bcd9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kindness_surveys',
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('praised_employee_id', sa.String(length=36), nullable=False),
    sa.Column('praise_comment', sa.Text(), nullable=False),
    sa.Column('improvement', sa.Text(), nullable=True),
    sa.Column('member_name', sa.String(length=50), nullable=False),
    sa.Column('member_phone', sa.String(length=30), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['praised_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kindness_surveys_praised_employee_id'), 'kindness_surveys', ['praised_employee_id'], unique=False)
    op.alter_column('score_events', 'created_by_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('score_events', 'created_by_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_kindness_surveys_praised_employee_id'), table_name='kindness_surveys')
    op.drop_table('kindness_surveys')
    # ### end Alembic commands ###
