"""leave reject reason

Revision ID: 8ba67c3e4737
Revises: 3fc796ddaecc
Create Date: 2026-07-24 04:44:00.670180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba67c3e4737'
down_revision: Union[str, Sequence[str], None] = '3fc796ddaecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('reject_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'reject_reason')
    # ### end Alembic commands ###
