"""reactions

Revision ID: 93c85d5a58cb
Revises: abefd2c2b134
Create Date: 2026-07-22 09:30:55.813509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c85d5a58cb'
down_revision: Union[str, Sequence[str], None] = 'abefd2c2b134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactions',
    sa.Column('target_type', sa.Enum('NOTICE', 'MEETING', 'MESSAGE', name='reactiontargettype', native_enum=False, length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('emoji', sa.String(length=32), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'emoji', 'employee_id', name='uq_reaction')
    )
    op.create_index(op.f('ix_reactions_target_id'), 'reactions', ['target_id'], unique=False)
    op.create_index(op.f('ix_reactions_target_type'), 'reactions', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactions_target_type'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_target_id'), table_name='reactions')
    op.drop_table('reactions')
    # ### end Alembic commands ###
