"""employee barcode

Revision ID: aa53051c62cd
Revises: 48183e38fa1b
Create Date: 2026-07-23 03:48:04.677602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa53051c62cd'
down_revision: Union[str, Sequence[str], None] = '48183e38fa1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('employees', sa.Column('barcode', sa.String(length=32), nullable=True))
    # 기존 직원 백필: 충돌 없는 8자리(10000001~) 순번 발급 (유니크 인덱스 생성 전)
    op.execute(
        """
        UPDATE employees e SET barcode = to_char(10000000 + s.rn, 'FM00000000')
        FROM (SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn FROM employees) s
        WHERE e.id = s.id
        """
    )
    op.create_index(op.f('ix_employees_barcode'), 'employees', ['barcode'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_barcode'), table_name='employees')
    op.drop_column('employees', 'barcode')
    # ### end Alembic commands ###
