"""peer_reviews

Revision ID: af33f832b4ac
Revises: cdf243a2ac5a
Create Date: 2026-07-22 07:45:03.413356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af33f832b4ac'
down_revision: Union[str, Sequence[str], None] = 'cdf243a2ac5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peer_reviews',
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('reviewee_id', sa.String(length=36), nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('competency', sa.Integer(), nullable=False),
    sa.Column('collaboration', sa.Integer(), nullable=False),
    sa.Column('contribution', sa.Integer(), nullable=False),
    sa.Column('attitude', sa.Integer(), nullable=False),
    sa.Column('leadership', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reviewer_id', 'reviewee_id', 'period', name='uq_peer_review')
    )
    op.create_index(op.f('ix_peer_reviews_period'), 'peer_reviews', ['period'], unique=False)
    op.create_index(op.f('ix_peer_reviews_reviewee_id'), 'peer_reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_peer_reviews_reviewer_id'), 'peer_reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peer_reviews_reviewer_id'), table_name='peer_reviews')
    op.drop_index(op.f('ix_peer_reviews_reviewee_id'), table_name='peer_reviews')
    op.drop_index(op.f('ix_peer_reviews_period'), table_name='peer_reviews')
    op.drop_table('peer_reviews')
    # ### end Alembic commands ###
