"""rank_policies, payslips, employee deduction_method

Revision ID: b4a82aeaecd8
Revises: 684a81169a44
Create Date: 2026-07-22 07:57:49.483445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a82aeaecd8'
down_revision: Union[str, Sequence[str], None] = '684a81169a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank_policies',
    sa.Column('rank', sa.Enum('JUNIOR_TRAINER', 'PRO_TRAINER', 'PRO1_TRAINER', 'TEAM_LEAD', 'STORE_MANAGER', 'FC', name='rank', native_enum=False, length=20), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.Column('new_rate', sa.Float(), nullable=False),
    sa.Column('renewal_rate', sa.Float(), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_policies_rank'), 'rank_policies', ['rank'], unique=False)
    op.create_table('payslips',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('rank', sa.Enum('JUNIOR_TRAINER', 'PRO_TRAINER', 'PRO1_TRAINER', 'TEAM_LEAD', 'STORE_MANAGER', 'FC', name='rank', native_enum=False, length=20), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.Column('incentive_new', sa.Integer(), nullable=False),
    sa.Column('incentive_renewal', sa.Integer(), nullable=False),
    sa.Column('other_allowances', sa.Integer(), nullable=False),
    sa.Column('gross', sa.Integer(), nullable=False),
    sa.Column('deduction_method', sa.Enum('FREELANCE', 'INSURANCE', name='deductionmethod', native_enum=False, length=20), nullable=False),
    sa.Column('deductions', sa.JSON(), nullable=False),
    sa.Column('total_deduction', sa.Integer(), nullable=False),
    sa.Column('net', sa.Integer(), nullable=False),
    sa.Column('basis', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year_month', name='uq_payslip')
    )
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_year_month'), 'payslips', ['year_month'], unique=False)
    op.add_column('employees', sa.Column('deduction_method', sa.Enum('FREELANCE', 'INSURANCE', name='deductionmethod', native_enum=False, length=20), server_default='FREELANCE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'deduction_method')
    op.drop_index(op.f('ix_payslips_year_month'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_rank_policies_rank'), table_name='rank_policies')
    op.drop_table('rank_policies')
    # ### end Alembic commands ###
