"""env items, task logs, supply orders

Revision ID: cdf243a2ac5a
Revises: 4ff640988ab8
Create Date: 2026-07-22 07:40:38.313294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf243a2ac5a'
down_revision: Union[str, Sequence[str], None] = '4ff640988ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env_items',
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_env_items_branch_id'), 'env_items', ['branch_id'], unique=False)
    op.create_table('env_task_logs',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('env_item_id', sa.String(length=36), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['env_item_id'], ['env_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_env_task_logs_branch_id'), 'env_task_logs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_env_task_logs_employee_id'), 'env_task_logs', ['employee_id'], unique=False)
    op.create_table('supply_orders',
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('ordered_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_orders_branch_id'), 'supply_orders', ['branch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_orders_branch_id'), table_name='supply_orders')
    op.drop_table('supply_orders')
    op.drop_index(op.f('ix_env_task_logs_employee_id'), table_name='env_task_logs')
    op.drop_index(op.f('ix_env_task_logs_branch_id'), table_name='env_task_logs')
    op.drop_table('env_task_logs')
    op.drop_index(op.f('ix_env_items_branch_id'), table_name='env_items')
    op.drop_table('env_items')
    # ### end Alembic commands ###
