"""employee emp_no

Revision ID: e5f5add80ce9
Revises: 3fa459100bed
Create Date: 2026-07-23 09:29:37.786690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f5add80ce9'
down_revision: Union[str, Sequence[str], None] = '3fa459100bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('employees', sa.Column('emp_no', sa.String(length=16), nullable=True))
    # 기존 직원 백필: {입사연도}-{4자리 순번} (연도별 joined_at 순)
    op.execute(
        """
        UPDATE employees e SET emp_no = sub.no FROM (
          SELECT id,
            to_char(joined_at, 'YYYY') || '-' ||
            lpad(row_number() OVER (
              PARTITION BY date_part('year', joined_at) ORDER BY joined_at, id
            )::text, 4, '0') AS no
          FROM employees
        ) sub WHERE e.id = sub.id
        """
    )
    op.create_index(op.f('ix_employees_emp_no'), 'employees', ['emp_no'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_emp_no'), table_name='employees')
    op.drop_column('employees', 'emp_no')
    # ### end Alembic commands ###
