"""approvals

Revision ID: f15e6a58b17f
Revises: 33c867be67e5
Create Date: 2026-07-22 09:12:13.604191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f15e6a58b17f'
down_revision: Union[str, Sequence[str], None] = '33c867be67e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('place', sa.String(length=200), nullable=True),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('approver_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'APPROVED', 'REJECTED', name='approvalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('current_approver_id', sa.String(length=36), nullable=True),
    sa.Column('comments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_approver_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_current_approver_id'), 'approvals', ['current_approver_id'], unique=False)
    op.create_index(op.f('ix_approvals_requester_id'), 'approvals', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_requester_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_current_approver_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
