"""invite rank, employee rank not null

Revision ID: ff8a4cbd0ec9
Revises: 15142a0a9d39
Create Date: 2026-07-22 06:38:09.347045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8a4cbd0ec9'
down_revision: Union[str, Sequence[str], None] = '15142a0a9d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'rank',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('invite_keys', sa.Column('rank', sa.Enum('JUNIOR_TRAINER', 'PRO_TRAINER', 'PRO1_TRAINER', 'TEAM_LEAD', 'STORE_MANAGER', 'FC', name='rank', native_enum=False, length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite_keys', 'rank')
    op.alter_column('employees', 'rank',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
